name: Continuous Integration

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    # azurite
    - name: Install Azurite
      id: azuright
      uses: potatoqualitee/azuright@v1.1
      with:
        self-signed-cert: true
    # restore dependencies  
    - name: Install dependencies
      run: dotnet restore
      working-directory: .\src
    # build
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: .\src
    - name: Test
      run: dotnet test
      working-directory: .\src
